from typing import Any, Protocol


class DataProvider(Protocol):
    """Provider contract consumed by ETL; domain code does not depend on a vendor."""

    def get(self, endpoint: str, **params: Any) -> list[dict[str, Any]]: ...

    def competitions(self, country: str | None = None) -> list[dict[str, Any]]: ...

    def seasons(self, league_id: int) -> list[dict[str, Any]]: ...

    def teams(self, league_id: int, season: int) -> list[dict[str, Any]]: ...

    def fixtures(self, league_id: int, season: int) -> list[dict[str, Any]]: ...

    def events(self, fixture_id: int) -> list[dict[str, Any]]: ...

    def statistics(self, fixture_id: int) -> list[dict[str, Any]]: ...

    def standings(self, league_id: int, season: int) -> list[dict[str, Any]]: ...
